language: r
r: 
  - 4.0.3
  
sudo: required

branches:
  only:
  - main

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "renv::restore()"

before_script:
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh 